### ISSUE TITLE
[question] saiku version?

### ISSUE THREAD

**Issue by valugi** [brenopolanski/saiku-plugin-boilerplate#20]
Is this plugin boilerplate specific for a certain saiku version? If so I think this could be specified.
Thanks

**Comment by brenopolanski** [comment]
Hey @valugi.

What version of Saiku you are having problems?

**Comment by valugi** [comment]
I use 2.5 and I did some modifications in order for this to work. I suppose this is for version 3+ correct?

**Comment by brenopolanski** [comment]
yeah @valugi.

I tested in version 2.6 and 3+.
